# Generated by Django 6.1.1 on 2026-09-23 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Soru / Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama / Bağlam')),
                ('category', models.CharField(choices=[('genel', 'Genel'), ('yemek', 'Yemek & Mutfak'), ('teknoloji', 'Teknoloji & Cihazlar'), ('moda', 'Moda & Stil'), ('dizi-film', 'Dizi & Film'), ('oyun', 'Oyun & Espor'), ('egitim', 'Eğitim & Kariyer'), ('alisveris', 'Alışveriş'), ('spor', 'Spor & Fitness'), ('diger', 'Diğer')], default='genel', max_length=50, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Seçenek Metni')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Sıra')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='Bağlı Anket')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Misafir Oturum Anahtarı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oy Tarihi')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option', verbose_name='Seçilen Seçenek')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll', verbose_name='Anket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_votes', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Oy',
                'verbose_name_plural': 'Oylar',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('poll', 'user'), name='unique_user_poll_vote'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('poll', 'session_key'), name='unique_session_poll_vote')],
            },
        ),
    ]
